### Create a new order to customer 1
POST http://localhost:3000/customers/1/orders HTTP/1.1
Content-Type: application/json

{
  "description": "123 - Box XPTO - 3"
}

### Try create a new order to invalid customer
POST http://localhost:3000/customers/543/orders HTTP/1.1
Content-Type: application/json

{
  "description": "123 - Box XPTO - 3"
}

### Start delivery to a order
PUT http://localhost:3000/customers/1/orders/2/init_delivery HTTP/1.1
Content-Type: application/json


### Done delivery to a order
PUT http://localhost:3000/customers/1/orders/2/finish_delivery HTTP/1.1
Content-Type: application/json


