version: '3'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0' -p 3000"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - sidekiq
    env_file:
      - .env
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  redis:
    driver: local